name: Deploy Hoth

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "hoth/**"

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      hoth: ./hoth

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      # Setup and configure gcloud CLI
      # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #   with:
      #     version: "290.0.1"
      #     project_id: ${{ secrets.project_id }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY}}

      - name: Declare GitHub Hash and Branch
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Create config.json
        run: |
          touch config.json
          echo "{}" > config.json
        working-directory: ${{env.hoth}}

      - name: Set Database Secrets
        uses: jossef/action-set-json-field@v1
        with:
          file: ./hoth/config.json
          field: ${{ secrets.DATABASE_KEY }}
          value: ${{ secrets.DATABASE_VALUE }}

      - name: Set JWT Secrets
        uses: jossef/action-set-json-field@v1
        with:
          file: ./hoth/config.json
          field: ${{ secrets.JWT_SECRET_KEY }}
          value: ${{ secrets.JWT_SECRET_VALUE }}

      - name: Set NBA API Secrets
        uses: jossef/action-set-json-field@v1
        with:
          file: ./hoth/config.json
          field: ${{ secrets.NBA_API_KEY }}
          value: ${{ secrets.NBA_API_VALUE }}

      - name: Fetch LFS Files
        run: git lfs checkout

      - name: Deploy Hoth
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.project_id }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: "hoth-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}"
          working_directory: ${{env.hoth}}
