name: Deploy Cron

on:
  push:
    branches:
      - main
      - dev
      - cron-setup
    paths:
      - "cron.yaml"

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.project_id }}
          service_account_key: ${{ secrets.GCP_SA_KEY}}

      # Deploy App to App Engine
      - name: Deploy Backend
        run: gcloud app deploy cron.yaml
