name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      frontend: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.project_id }}
          service_account_key: ${{ secrets.GCP_SA_KEY}}

      - name: Declare GitHub Hash and Branch
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # Deploy App to App Engine
      - name: Deploy Fronted
        run: |
          export REACT_APP_VERSION=frontend-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
          npm ci
          npm run build
          gcloud app deploy --quiet --version="frontend-${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}"
        working-directory: ${{env.frontend}}
