on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - "frontend/**"

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    env:
      frontend: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Fronted
        run: |
          npm ci
          npm run build
        working-directory: ${{env.frontend}}
